### Config for loading and rendering trained camas models
env: camas

env_args:
  map_name: "grid-small"
  
  # Possible observation types: 
  #     global: [agent position, other agent positions.. ]
  #     context: [agent position, context of edges..  ]
  observation_type: "global" # needs to match model being loaded

  # Divide reward by this factor before outputting
  reward_scaling_factor: 100

  # Mean and variance for Phase Type Distributions is calculated as:
  #     i*mean+1, var*(i+1)
  # where i is the congestion band and mean and var are set below.
  ptd_mean: 1.0
  ptd_var: 0.1

  # Rewards
  goal_reward: 0
  time_multiplier: 1

  debug: False
  seed: Null


runner: "render"
gamma: 0.99
epsilon_anneal_time: 500000

test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000

t_max: 5100000  # This must be greater than the timestep being loaded

use_tensorboard: False # Log results to tensorboard
save_model: False
checkpoint_path: "results/models/qmix__2022-02-28_00-02-36" # Load a checkpoint from this path
load_step: 0 