env: camas

env_args:
  map_name: "grid-small"
  # Number of agents to use in the environment
  #     0: maximum number of agents
  #     Will return an error if number specifed is more than the maximum for the given map.
  agent_count: 0
  episode_limit: 1000
  
  # Possible observation types: 
  #     global: [agent position, other agent positions.. ]
  #     context: [agent position, context of edges..  ]
  observation_type: "context"

  # Divide reward by this factor before outputting
  reward_scaling_factor: 200

  # Mean and variance for Phase Type Distributions is calculated as:
  #     i*mean+1, var*(i+1)
  # where i is the congestion band and mean and var are set below.
  ptd_mean: 1.0
  ptd_var: 0.1

  # Rewards
  goal_reward: 30
  time_multiplier: -1

  debug: False
  seed: Null


runner: "async"
gamma: 0.99
epsilon_anneal_time: 2500000

test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000

t_max: 5000000

save_model: True
save_model_interval: 500000
#checkpoint_path: "results/models/qmix__2022-02-27_15-03-52/2000446" # Load a checkpoint from this path