!!python/object/apply:types.SimpleNamespace
state:
  action_selector: epsilon_greedy
  agent: rnn
  agent_output_type: q
  batch_size: 32
  batch_size_run: 1
  buffer_cpu_only: false
  buffer_size: 5000
  checkpoint_path: ''
  critic_lr: 0.0005
  device: cuda
  double_q: true
  env: camas
  env_args:
    agent_count: 10
    congestion: true
    debug: false
    dummy_actions: true
    episode_limit: 0
    goal_reward: 200
    map_name: warehouse-large
    observation_type: context
    ptd_mean: 1
    ptd_var: 0.1
    reward_scaling_factor: 100
    reward_type: time-cost
    seed: null
    time_multiplier: -25
    two_bands_only: false
  epsilon_anneal_time: 2000000
  epsilon_finish: 0.05
  epsilon_start: 1.0
  evaluate: false
  gamma: 0.99
  grad_norm_clip: 10
  hypernet_embed: 64
  hypernet_layers: 2
  label: default_label
  learner: q_learner
  learner_log_interval: 20000
  load_step: 0
  local_results_path: results
  log_interval: 20000
  lr: 0.0005
  mac: basic_mac
  mixer: qmix
  mixing_embed_dim: 32
  n_actions: 5
  n_agents: 10
  name: qmix
  obs_agent_id: true
  obs_last_action: true
  optim_alpha: 0.99
  optim_eps: 1.0e-05
  per_alpha: 1.0
  per_beta: 0.4
  per_beta_anneal: 0.7
  per_epsilon: 1.0
  per_reward_power: 8
  prioritised_replay: false
  repeat_id: 1
  rnn_hidden_dim: 64
  runner: timelim
  runner_log_interval: 50000
  save_mac_weights: true
  save_model: true
  save_model_interval: 500000
  save_replay: false
  state_shape: !!python/tuple
  - 10
  t_max: 12010000
  target_update_interval: 200
  test_greedy: true
  test_interval: 50000
  test_nepisode: 32
  train_twice: false
  unique_token: curriculum_qmix__2022-04-10_22-13-34
  use_cuda: true
  use_tensorboard: true
